### ISSUE TITLE
save_feature function in feature.py?

### ISSUE THREAD

**Issue by nianniandoushabao** [ozora-ogino/LCNN#1]
The feature.py doesn't have a save_feature function.So may I have your ' save_feature function' code ?

**Comment by ozora-ogino** [comment]
@nianniandoushabao  Sorry, I didn't know that.
It just a function which wrap `pickle`.
I'll share it later!

**Comment by ozora-ogino** [comment]
@nianniandoushabao Sorry for late.
I added `save_feature` in `feature.py`.
