### ISSUE TITLE
Script works for PA attack only?

### ISSUE THREAD

**Issue by AnkitaBeniwal** [ozora-ogino/LCNN#2]
The protocol files include the PA files as csv. Does this script work for LA attack as well?

**Comment by ozora-ogino** [comment]
@AnkitaBeniwal Thank you for asking.
I'm not sure if my scripts can works with LA dataset and also model performance too.

**Comment by AnkitaBeniwal** [comment]
Thank you for your quick response. Mind if I ask, Is there a specific way of generating .csv files in the protocols folder?

**Comment by ozora-ogino** [comment]
@AnkitaBeniwal It was generated my own script.
I'll share if I can find it but I'm not sure I still have it ...

**Comment by AnkitaBeniwal** [comment]
> @AnkitaBeniwal It was generated my own script.
> I'll share if I can find it but I'm not sure I still have it ...

if you do find, could you please share it at beniwalanky@gmail.com. Thanks in advance!

**Comment by ozora-ogino** [comment]
@AnkitaBeniwal I added it in [protocol/generate_proto.py ](https://github.com/ozora-ogino/LCNN/blob/master/protocol/generate_proto.py).
For the others, I'd like to upload it instead of send it to your email.

**Comment by ozora-ogino** [comment]
@AnkitaBeniwal 
BTW, I've never used it for LA so you may need to change `cols` in `convert_txt_to_csv`.
