### ISSUE TITLE
Getting a Value Error

### ISSUE THREAD

**Issue by AnkitaBeniwal** [ozora-ogino/LCNN#3]
The train and dev features get extracted successfully; While building the LCNN model, I get the following error:
ValueError: Input 0 of layer conv2d is incompatible with the layer: : expected min_ndim=4, found ndim=3.
I did not make any changes in the script, simply running the original script with same dataset (ASV spoof 2019)
![Screenshot 2021-09-24 at 9 41 16 PM](https://user-images.githubusercontent.com/34271099/134684236-22f96df7-d235-4f9c-97a4-b3d84e8f7806.png)

**Comment by ozora-ogino** [comment]
@AnkitaBeniwal 
Which feature type did you used?

**Comment by AnkitaBeniwal** [comment]
> @AnkitaBeniwal
> Which feature type did you used?

CQT. from get_cqt function. Was by default selected.

**Comment by ozora-ogino** [comment]
@AnkitaBeniwal All right.
I fixed bugs.
Cloud you try it again after pull the latest version?

**Comment by AnkitaBeniwal** [comment]
> @AnkitaBeniwal All right.
> I fixed bugs.
> Cloud you try it again after pull the latest version?

Alright. Thanks alot. Let me try it.

**Comment by ozora-ogino** [comment]
@AnkitaBeniwal NOP👍
If the scripts works, let me know.
I'll close this issue.

**Comment by ozora-ogino** [comment]
@AnkitaBeniwal Can i close this issue?

**Comment by AnkitaBeniwal** [comment]
> @AnkitaBeniwal Can i close this issue?

Oh yes. Thanks a million.
