### ISSUE TITLE
Request for more details

### ISSUE THREAD

**Issue by ghost** [ozora-ogino/LCNN#6]
I appreciate that your code can be used as a reference, but I don't know how to run them, could you please add more comments in the README file again? Thanks.

**Comment by ozora-ogino** [comment]
@qiwu000 Thank you for reporting this issue.

train.py is the main interface.

**Comment by ghost** [comment]
！！Thank you very much for your reply. I'll try to learn and do it！

**Comment by ghost** [comment]
I don't have a lot of foundation but would like to try to run your code and understand a little bit, can you give me some advice ? Thank you!
